// @ts-check
import tseslint from "typescript-eslint";
import eslintPluginAstro from "eslint-plugin-astro";

export default tseslint.config(
  ...tseslint.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  {
    // Worker workspace package (007): type-aware linting against its own tsconfig.
    files: ["worker/**/*.ts"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
    },
  },
  {
    ignores: [
      "dist/**",
      ".astro/**",
      ".wrangler/**",
      // Generated by `wrangler types`; checked with `--check`, not linted.
      "worker/worker-configuration.d.ts",
      "node_modules/**",
      // Fixture-site builds write here (tests/build, scripts/build-fixture-site.ts).
      ".cache/**",
      "test-results/**",
      "playwright-report/**",
      // Read-only design reference (Flux theme), gitignored and never
      // imported (FR-033) — not this repository's code to lint.
      ".reference/**",
    ],
  },
);
